samples:
  - HNES1_DUX4_overexpression_L001
  - HNES1_wildtype_L001


#################
## Directories ##
#################

directories:
    base: /bi/group/reik/ricard/data/DUX4_hESCs_multiome
    original_data: /bi/group/reik/ricard/data/DUX4_hESCs_multiome/original
    processed_data: /bi/group/reik/ricard/data/DUX4_hESCs_multiome/processed/atac/archR
    results: /bi/group/reik/ricard/data/DUX4_hESCs_multiome/results/atac/archR

files:
    rna_metadata: /bi/group/reik/ricard/data/DUX4_hESCs_multiome/results/rna/clustering/sample_metadata_after_clustering.txt.gz
    
#############
## Scripts ##
#############

scripts:
    create_arrow_files: ../atac/archR/processing/0_create_arrow_files.R
    create_archr_project: ../atac/archR/processing/1_create_archR_project.R
    create_archr_metadata: ../atac/archR/processing/2_create_archR_metadata.R
    qc_archr: ../atac/archR/processing/3_qc.R
    add_gene_scores: ../atac/archR/gene_scores/add_GeneScore_matrices.R
    pseudobulk_add_group_coverage: ../atac/archR/pseudobulk/1_archR_add_GroupCoverage.R
    pseudobulk: ../atac/archR/pseudobulk/2_archR_pseudobulk_celltypes.R
    dimensionality_reduction: ../atac/archR/dimensionality_reduction/automated/archR_dimensionality_reduction.R
    peak_calling: ../atac/archR/peak_calling/peak_calling_archR.R
    gene_scores: ../atac/archR/gene_scores/add_GeneScore_matrices.R
    create_bigwigs: ../atac/archR/bigwig/archR_export_bw.R
    add_motif_annotation: ../atac/archR/add_motif_annotation/archR_add_motif_annotation.R



################
## Parameters ##
################

create_arrow_files:
    genome: "hg38"
    min_fragments: 1000
    max_fragments: 1000000
    min_tss_score: 2.5
    # threads: 2

create_archr_project:
    genome: "hg38"

create_archr_metadata:
    genome: "hg38"

qc_archr:
    min_tss_enrichment: 8
    min_number_fragments: 3000
    max_blacklist_ratio: 0.05
    # threads: 2

pseudobulk_add_group_coverage:
    group_by: "cluster"
    min_cells: 25
    max_cells: 100
    # threads: 2

peak_calling:
    group_by: "cluster"
    pathToMacs2: "/bi/group/reik/ricard/software/miniconda3/envs/main/bin/macs2"
    pvalue_cutoff: 0.001
    extend_summits: 300
    # threads: 2

create_bigwigs:
    # group_by: ["cluster", "sample"]
    group_by: "cluster"
    norm_method: "ReadsInTSS"
    tile_size: 100
    # threads: 2

# add_motif_annotation:

###########
## Slurm ##
###########

slurm:  # memory in GB
    create_arrow_files: 
        threads: 1
        memory: 10
    create_archr_project:
        threads: 1
        memory: 10
    create_archr_metadata:
        threads: 1
        memory: 10
    qc_archr: 
        threads: 1
        memory: 10
    pseudobulk_add_group_coverage:
        threads: 1
        memory: 10
    peak_calling:
        threads: 1
        memory: 10
    gene_scores:
        threads: 1
        memory: 10
    create_bigwigs:
        threads: 1
        memory: 10
    add_motif_annotation:
        threads: 1
        memory: 10