samples:
  - HNES1_DUX4_overexpression_L001
  - HNES1_wildtype_L001


#################
## Directories ##
#################

directories:
    base: /Users/argelagr/data/DUX4_hESCs_multiome
    original_data: /Users/argelagr/data/DUX4_hESCs_multiome/original/rna
    processed_data: /Users/argelagr/data/DUX4_hESCs_multiome/processed/rna
    results: /Users/argelagr/data/DUX4_hESCs_multiome/results

#############
## Scripts ##
#############

scripts:
    create_seurat: ../rna/processing/1_create_seurat_rna.R
    qc: ../rna/processing/2_QC.R
    seurat_to_sce: ../rna/processing/3_seurat_to_SCE.R
    doublet_detection: ../rna/processing/4_doublet_detection.R
    parse_doublets: ../rna/processing/5_parse_sample_metadata_after_doublets.R
    dimensionality_reduction: ../rna/dimensionality_reduction/automated/dimensionality_reduction_sce.R


################
## Parameters ##
################

doublet_detection:
    doublet_score_threshold: 1.25

dimensionality_reduction:
    npcs: 30
    features: 1000
    n_neighbors: 25
    min_dist: 0.3
    colour_by: ["sample", "doublet_score", "doublet_call"]