channels:
  - conda-forge
  - bioconda
dependencies:
  # - r-base =4.1.1
  # - r-tidyverse =1.2-1
  - bioconductor-scater =1.20
  - bioconductor-scran =1.20
  - bioconductor-singlecellexperiment =1.14
  - bioconductor-batchelor =1.8
  - bioconductor-scds =1.8
  # - r-xml2 =1.3.2
  - r-r.utils=2.11.0
  - r-ggpubr =0.4.0
  - r-argparse =2.1.1
  - r-seurat =4.0.4



